name: Build
on:
  push:
    branches: [ main ]
jobs:
  deploy:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: 'zulu'
            java-version: '21'

        - name: npm clean install
          run: ./sbt npmInstall

        - name: Run tests
          run: ./sbt test

        - name: Package Application
          run: ./sbt packageApp