name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Set up node
          uses: actions/setup-node@v4
          with:
            node-version: '22'

        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: 'zulu'
            java-version: '21'
            cache: 'sbt'

        - name: Set up sbt launcher
          uses: sbt/setup-sbt@v1

        - name: npm clean install
          run: sbt npmInstall

        - name: Run tests
          run: sbt test

        - name: Package Application
          run: sbt packageApp
          
  merge:
    name: Merge dependency update
    if: github.actor == 'scala-steward'
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Merge scala-steward PR
        uses: desbo/merge-pr-action@v0
        with:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          ALLOWED_UPDATE: minor
